In [3]:
import pandas as pd
raw_data = pd.read_excel("raw data.xlsx") # Load the raw dataset from an Excel file
raw_data.head(20) ## Show the first 20 rows to check the structure of the dataset

    W  Slip_plane  Temperature  Applied_stress  Velocity  Maximum_stress
0   0         110            0             0.5     12.68       852.44638
1   0         110            0             1.0     13.40      1764.06895
2   0         110            0             1.5     14.35      2673.03972
3   0         110          300             0.5     12.57       833.13348
4   0         110          300             1.0     13.30      1706.98713
5   0         110          300             1.5     14.04      2560.20202
6   0         110         1000             0.5     11.63       743.36036
7   0         110         1000             1.0     12.50      1498.75891
8   0         110         1000             1.5     12.82      2227.92861
9   0         110         2000             0.5      9.47       705.41306
10  0         110         2000             1.0     11.10      1397.50870
11  0         110         2000             1.5     11.42      2084.27821
12  0         112            0             0.5     14.63       909.45174
13  0         112            0             1.0     16.53      1899.53812
14  0         112            0             1.5     16.90      2887.21280
15  0         112          300             0.5     14.90       903.42762
16  0         112          300             1.0     16.47      1886.40897
17  0         112          300             1.5     16.84      2865.85675
18  0         112         1000             0.5     14.80       897.89763
19  0         112         1000             1.0     16.12      1879.09352

In [4]:
raw_data.tail(20) ## Show the last 20 rows to check the structure of the dataset

     W  Slip_plane  Temperature  Applied_stress  Velocity  Maximum_stress
88   5         112          300             1.0     16.02      1889.11929
89   5         112          300             1.5     16.57      2869.59700
90   5         112         1000             0.5     13.30       915.49913
91   5         112         1000             1.0     15.50      1892.54021
92   5         112         1000             1.5     16.26      2875.65945
93   5         112         2000             0.5     13.00       919.65484
94   5         112         2000             1.0     15.18      1897.02410
95   5         112         2000             1.5     15.93      2893.43807
96   5         123            0             0.5     12.25       909.09407
97   5         123            0             1.0     14.87      1881.01063
98   5         123            0             1.5     15.85      2862.61121
99   5         123          300             0.5     12.79       896.71851
100  5         123          300             1.0     14.87      1850.66871
101  5         123          300             1.5     15.66      2806.92192
102  5         123         1000             0.5     12.43       851.42706
103  5         123         1000             1.0     14.29      1782.20806
104  5         123         1000             1.5     15.17      2716.89155
105  5         123         2000             0.5     11.35       855.95904
106  5         123         2000             1.0     13.51      1756.16886
107  5         123         2000             1.5     15.20      2681.51702